apiVersion: marklogic.progress.com/v1
kind: MarklogicCluster
metadata:
  name: test-cluster
  annotations: {}
spec:
  image: "progressofficial/marklogic-db:11.3.0-ubi-rootless"
  ## It is recommended to use Kubernetes secrets to store the admin credentials
  ## To create a secret, run the following command in the same namespace as the CR:
  ## kubectl create secret generic admincreds --from-literal=username=admin --from-literal=password=admin
  ## If you do not provide the admin credentials, the operator will generate a secret for you containing admin credentials
  persistence:
    enabled: true
    size: 10Gi
  markLogicGroups:
  - replicas: 1
    name: node
    groupConfig:
      name: node
    # resources:
    #   requests:
    #     memory: "1Gi"
    #     cpu: 100m
    #   limits:
    #     memory: "1Gi"
    #     cpu: 100m
    isBootstrap: true

# 2. Add an annotation to pause upgrades
# kubectl annotate marklogiccluster single-node marklogic.com/upgrade-paused=true