apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: marklogic-storage
parameters:
  csi.storage.k8s.io/fstype: ext4
  encrypted: "false"
  iops: "3000"
  throughput: "125"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer